import { expect, test } from '@playwright/test';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

import config from '../playwright.config';
import {
  findBaselineViolations,
  inventoryFileName,
  pendingBaselines,
  treeIsStableDuring,
} from './visual-baselines';

const e2eDir = __dirname;
const projectNames = (config.projects ?? []).map((project) => project.name ?? '');

const treeProjects = ['desktop-chromium'];

type Tree = {
  /** Baselines the inventory presents as regenerated by the operator. */
  committed?: Record<string, string[]>;
  /** Baselines the inventory presents as still owed by the operator. */
  pending?: Record<string, string[]>;
  /** Baselines actually on disk, keyed by snapshot directory. */
  present?: Record<string, string[]>;
  /** Screenshot arguments each spec asserts, keyed by spec path. */
  specs?: Record<string, string[]>;
};

/**
 * The scan reads this spec too, so the assertion is assembled at runtime: a
 * literal call here would claim baselines this file never renders.
 */
function specSource(screenshotArguments: string[]): string {
  return screenshotArguments
    .map((argument) => `await expect(page).toHave${'Screenshot'}('${argument}');\n`)
    .join('');
}

/** A tree shaped like `e2e/`: the inventory, the specs, and the baselines on disk. */
function writeTree({ committed = {}, pending = {}, present = {}, specs = {} }: Tree): string {
  const root = mkdtempSync(path.join(tmpdir(), 'visual-baselines-'));
  writeFileSync(
    path.join(root, inventoryFileName),
    JSON.stringify({ directories: committed, pending }),
  );

  for (const [directory, names] of Object.entries(present)) {
    mkdirSync(path.join(root, directory), { recursive: true });
    for (const name of names) {
      writeFileSync(path.join(root, directory, name), '');
    }
  }

  for (const [spec, screenshotArguments] of Object.entries(specs)) {
    mkdirSync(path.dirname(path.join(root, spec)), { recursive: true });
    writeFileSync(path.join(root, spec), specSource(screenshotArguments));
  }

  return root;
}

test.describe('committed visual baselines', () => {
  const trees: string[] = [];

  test.afterAll(() => {
    for (const root of trees.splice(0)) {
      rmSync(root, { recursive: true, force: true });
    }
  });

  function tree(contents: Tree): string {
    const root = writeTree(contents);
    trees.push(root);
    return root;
  }

  test('every baseline in this repository is one the operator recorded', () => {
    // `reporter: 'list'` prints test stdout, so the run states what
    // `npm run test:e2e:web:visual` still owes it. This reads the inventory alone,
    // so it holds even in the run that rewrites the tree.
    const owed = pendingBaselines(e2eDir);
    if (owed.length > 0) {
      console.log(`Baselines awaiting the operator's validation image:\n  ${owed.join('\n  ')}`);
    }

    // That rewriting run is why the reconciliation below stands aside there: it
    // would read `e2e/` while another worker is still writing baselines into it.
    // Once the inventory owes nothing there is nothing left to write, so the
    // reconciliation runs even without `--ignore-snapshots`.
    test.skip(
      !treeIsStableDuring(test.info().project, owed),
      'This run regenerates the pending baselines, so the tree it would reconcile is still being written.',
    );

    expect(findBaselineViolations(e2eDir, projectNames)).toEqual([]);
  });

  // The reconciliation above is the only test that reads the real repository
  // tree, and it stands aside in a run that writes baselines. That is safe only
  // while the validation entrypoint passes the flag which stops the writing: if
  // this script ever drops it, the guard would report `skipped` in every
  // validation run instead of failing, and issue #84's protection would be gone
  // behind a green suite. Nothing else in the repository asserts that coupling.
  test('the validation entrypoint runs with the flag that keeps this guard enabled', () => {
    const manifest: unknown = JSON.parse(
      readFileSync(path.join(e2eDir, '..', 'package.json'), 'utf8'),
    );
    const scripts = (manifest as { scripts?: Record<string, string> }).scripts ?? {};

    expect(scripts['test:e2e']).toContain('--ignore-snapshots');
  });

  // Playwright spreads spec files across workers even with `fullyParallel: false`,
  // so during `npm run test:e2e:web:visual` this guard and the `toHaveScreenshot`
  // call that writes the pending PNGs run at the same time. A run told to ignore
  // snapshots writes nothing; so does any run with no baseline left to render,
  // which is what keeps the guard live for an agent following apps/web/AGENTS.md
  // and invoking `npx playwright test e2e/visual-baselines.spec.ts` directly.
  test('reconciles the repository tree in every run that writes no baselines', () => {
    const owed = ['profile.spec.ts-snapshots/password-change-form-desktop-chromium.png'];

    expect(treeIsStableDuring({ ignoreSnapshots: true }, owed)).toBe(true);
    expect(treeIsStableDuring({ ignoreSnapshots: false }, [])).toBe(true);
    expect(treeIsStableDuring({}, [])).toBe(true);
    expect(treeIsStableDuring({ ignoreSnapshots: false }, owed)).toBe(false);
    expect(treeIsStableDuring({}, owed)).toBe(false);
  });

  // The failure this guard exists for: a session adds a visual assertion and
  // writes the PNGs its own browser rendered, which no run ever compares.
  test('reports a baseline the inventory does not list', () => {
    const root = tree({
      committed: { 'profile.spec.ts-snapshots': ['listed-desktop-chromium.png'] },
      present: {
        'profile.spec.ts-snapshots': ['listed-desktop-chromium.png', 'agent-desktop-chromium.png'],
      },
      specs: { 'profile.spec.ts': ['listed.png', 'agent.png'] },
    });

    expect(findBaselineViolations(root, treeProjects)).toEqual([
      expect.stringContaining('profile.spec.ts-snapshots/agent-desktop-chromium.png'),
    ]);
  });

  test('reports a baseline in a snapshot directory the inventory omits entirely', () => {
    const root = tree({
      present: { 'files-panel.spec.ts-snapshots': ['agent-desktop-chromium.png'] },
      specs: { 'files-panel.spec.ts': ['agent.png'] },
    });

    expect(findBaselineViolations(root, treeProjects)).toEqual([
      expect.stringContaining('files-panel.spec.ts-snapshots/agent-desktop-chromium.png'),
    ]);
  });

  // `snapshotPathTemplate` embeds the spec path, so a spec in a subdirectory
  // keeps its baselines there too.
  test('reports a baseline in a snapshot directory nested below the test directory', () => {
    const root = tree({
      present: { 'profile/password.spec.ts-snapshots': ['agent-desktop-chromium.png'] },
      specs: { 'profile/password.spec.ts': ['agent.png'] },
    });

    expect(findBaselineViolations(root, treeProjects)).toEqual([
      expect.stringContaining('profile/password.spec.ts-snapshots/agent-desktop-chromium.png'),
    ]);
  });

  test('reports an inventory entry whose file is gone', () => {
    const root = tree({
      committed: { 'profile.spec.ts-snapshots': ['renamed-desktop-chromium.png'] },
      present: { 'profile.spec.ts-snapshots': [] },
      specs: { 'profile.spec.ts': ['renamed.png'] },
    });

    expect(findBaselineViolations(root, treeProjects)).toEqual([
      expect.stringContaining('profile.spec.ts-snapshots/renamed-desktop-chromium.png'),
    ]);
  });

  // A renamed spec leaves its whole snapshot directory behind, and every name in
  // it still matches a file, so only the missing assertion gives it away.
  test('reports a listed baseline that no screenshot assertion produces', () => {
    const root = tree({
      committed: {
        'profile.spec.ts-snapshots': ['orphan-desktop-chromium.png'],
        'account.spec.ts-snapshots': ['orphan-desktop-chromium.png'],
      },
      present: {
        'profile.spec.ts-snapshots': ['orphan-desktop-chromium.png'],
        'account.spec.ts-snapshots': ['orphan-desktop-chromium.png'],
      },
      specs: { 'account.spec.ts': ['orphan.png'] },
    });

    expect(findBaselineViolations(root, treeProjects)).toEqual([
      expect.stringContaining('profile.spec.ts-snapshots/orphan-desktop-chromium.png'),
    ]);
  });

  test('reports a screenshot assertion with neither a baseline nor a pending entry', () => {
    const root = tree({ specs: { 'profile.spec.ts': ['password-change-form.png'] } });

    expect(findBaselineViolations(root, treeProjects)).toEqual([
      expect.stringContaining(
        'profile.spec.ts-snapshots/password-change-form-desktop-chromium.png',
      ),
    ]);
  });

  test('accepts an assertion whose baseline the inventory records as pending', () => {
    const root = tree({
      pending: { 'profile.spec.ts-snapshots': ['password-change-form-desktop-chromium.png'] },
      specs: { 'profile.spec.ts': ['password-change-form.png'] },
    });

    expect(findBaselineViolations(root, treeProjects)).toEqual([]);
  });

  test('reports a pending entry whose baseline has since been regenerated', () => {
    const root = tree({
      pending: { 'profile.spec.ts-snapshots': ['regenerated-desktop-chromium.png'] },
      present: { 'profile.spec.ts-snapshots': ['regenerated-desktop-chromium.png'] },
      specs: { 'profile.spec.ts': ['regenerated.png'] },
    });

    expect(findBaselineViolations(root, treeProjects)).toEqual([
      expect.stringContaining('profile.spec.ts-snapshots/regenerated-desktop-chromium.png'),
    ]);
  });

  test('names every pending baseline for the operator', () => {
    const root = tree({
      pending: {
        'profile.spec.ts-snapshots': ['password-change-form-desktop-chromium.png'],
      },
      specs: { 'profile.spec.ts': ['password-change-form.png'] },
    });

    expect(pendingBaselines(root)).toEqual([
      'profile.spec.ts-snapshots/password-change-form-desktop-chromium.png',
    ]);
  });

  test('ignores directories that are not snapshot directories', () => {
    const root = tree({
      committed: { 'profile.spec.ts-snapshots': ['listed-desktop-chromium.png'] },
      present: {
        'profile.spec.ts-snapshots': ['listed-desktop-chromium.png'],
        fixtures: ['avatar.png'],
      },
      specs: { 'profile.spec.ts': ['listed.png'] },
    });

    expect(findBaselineViolations(root, treeProjects)).toEqual([]);
  });

  test('ignores a directory nested inside a snapshot directory', () => {
    const root = tree({
      committed: { 'profile.spec.ts-snapshots': ['listed-desktop-chromium.png'] },
      present: {
        'profile.spec.ts-snapshots': ['listed-desktop-chromium.png'],
        'profile.spec.ts-snapshots/retry-1': [],
      },
      specs: { 'profile.spec.ts': ['listed.png'] },
    });

    expect(findBaselineViolations(root, treeProjects)).toEqual([]);
  });

  test('rejects an inventory that does not describe directories', () => {
    const root = mkdtempSync(path.join(tmpdir(), 'visual-baselines-'));
    trees.push(root);
    writeFileSync(path.join(root, inventoryFileName), JSON.stringify({ directories: [] }));

    expect(() => findBaselineViolations(root, treeProjects)).toThrow(/must be an object/);
  });

  test('rejects an inventory whose pending list is not an array of names', () => {
    const root = mkdtempSync(path.join(tmpdir(), 'visual-baselines-'));
    trees.push(root);
    writeFileSync(
      path.join(root, inventoryFileName),
      JSON.stringify({ directories: {}, pending: { 'profile.spec.ts-snapshots': [7] } }),
    );

    expect(() => findBaselineViolations(root, treeProjects)).toThrow(/array of names/);
  });
});
